// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: order.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderTransfer_CreateOrder_FullMethodName = "/order.OrderTransfer/CreateOrder"
)

// OrderTransferClient is the client API for OrderTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderTransferClient interface {
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
}

type orderTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderTransferClient(cc grpc.ClientConnInterface) OrderTransferClient {
	return &orderTransferClient{cc}
}

func (c *orderTransferClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderTransfer_CreateOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderTransferServer is the server API for OrderTransfer service.
// All implementations must embed UnimplementedOrderTransferServer
// for forward compatibility
type OrderTransferServer interface {
	CreateOrder(context.Context, *Order) (*Order, error)
	mustEmbedUnimplementedOrderTransferServer()
}

// UnimplementedOrderTransferServer must be embedded to have forward compatible implementations.
type UnimplementedOrderTransferServer struct {
}

func (UnimplementedOrderTransferServer) CreateOrder(context.Context, *Order) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderTransferServer) mustEmbedUnimplementedOrderTransferServer() {}

// UnsafeOrderTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderTransferServer will
// result in compilation errors.
type UnsafeOrderTransferServer interface {
	mustEmbedUnimplementedOrderTransferServer()
}

func RegisterOrderTransferServer(s grpc.ServiceRegistrar, srv OrderTransferServer) {
	s.RegisterService(&OrderTransfer_ServiceDesc, srv)
}

func _OrderTransfer_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderTransferServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderTransfer_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderTransferServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderTransfer_ServiceDesc is the grpc.ServiceDesc for OrderTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderTransfer",
	HandlerType: (*OrderTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderTransfer_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
